version: 2.1
executors:
  my-custom-executor:
    resource_class: sucicada/test
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/SuCicada/test-github-action/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  build:
    executor: my-custom-executor
    steps:
      - checkout
      - run: echo "Hello, world!"
  my-job-name:
    machine: true
    resource_class: sucicada/test
    # executor: my-custom-executor
    steps:
      - checkout
      - run: |
          ls
          pwd
          sleep 60
          echo "export TEST_NAME=nihaonihaoh" >> test.sh
          # docker run --rm ubuntu cat /etc/os-release
          source test.sh && bash test.sh
          bash -c "source ~/.bashrc && bash test.sh"
      - run: echo "Hello, world!"aaa

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name
      - build