# workflow的名称，会显示在github 的项目的Actions的右边列表中，如下图
name: Build

# 在满足以下条件触发这个workflow
on:
  issues:
    types: [ opened ]
    # 指定文件发生修改
#    paths:
#      - 'config.gradle'
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      # step：检查分支
      - name: Checkout # 将仓库内master分支的内容下载到工作目录
        uses: actions/checkout@v1
      # step：设置jdk版本
      - name: set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      # step：打包apk
      - name: Build with Gradle
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
#        chmod +x gradlew &&./gradlew assembleRelease