# workflow的名称，会显示在github 的项目的Actions的右边列表中，如下图
name: Build

# 在满足以下条件触发这个workflow
on:
  issues:
    types: [ opened,labeled ]
    # 指定文件发生修改
#    paths:
#      - 'config.gradle'
permissions:
  issues: write

jobs:
  first-job:
    if: ${{ github.event.label.name == 'build' }}
    runs-on: ubuntu-latest
    steps:
      # step：检查分支
      - name: Checkout # 将仓库内master分支的内容下载到工作目录
        uses: actions/checkout@v1
      # step：设置jdk版本
#      - name: set up JDK 8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 8
      # step：打包apk
      - name: Build with Gradle
        id: issue
        env:
          TITLE: ${{ github.event.issue.title }}
        run: |
          echo "Issue title: $TITLE"
          echo "Issue body: ${{ github.event.issue.body }}"
          echo "::set-output name=title::$TITLE"
      #        chmod +x gradlew &&./gradlew assembleRelease

      - name: sd sdf
        env:
          BODY: ${{ steps.issue.outputs.title }}
        run: |
            echo ${{env.BODY}}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'