name: Build

on:
  push

# permissions of github action bot
permissions: write-all
#  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v3
      - name: Set up Python
        run: |
          sh test.sh